version: '3.8'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
    ports:
      - "8006:8006"    # noVNC Web
      - "3389:3389"    # RDP TCP
      - "3389:3389/udp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./windows:/storage
    restart: unless-stopped

  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: dev
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - windows

